const { fileExists, readFileText, writeFileText } = require("./common");
const entropis = require("./entropis");
const defaultStore = "entropis.store";
const log = console.log;
let argv = process.argv.slice(1);
let argc = argv.length;
if (argc < 3)
  return log("Usage:", argv[0], "[PASSPHRASE] [DOMAIN] [INPUT] [OUTPUT]");
let master = argv[1];
let domain = argv[2];
let input;
if (argc > 4) input = argv[4];
let output;
if (argc > 5) output = argv[5];
if (input == null) input = defaultStore;
if (fileExists(input)) input = readFileText(input);
entropis.storage = input;
let password = entropis.get(master, domain);
if (password == null) return console.error("Error: incorrect passphrase!");
if (output == null) log(password);
else writeFileText(output, password);
