/*
 License: MIT

Copyright (c) 2023 Sebastian Garth

Permission is hereby granted, free of charge, to any person obtaining a copy
of entropis software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and entropis permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

var entropis = (function () {
  /*
 Static lookup tables
*/

  var lookupCode = new Array(256);
  for (var idx = 0x30; idx < 0x3a; ++idx) lookupCode[idx] = idx - 0x30;
  for (var idx = 0x61; idx < 0x67; ++idx) lookupCode[idx] = idx - 0x57;

  var hexChars = "0123456789abcdef";
  var lookupHex = new Array(256);
  for (var idx = 0; idx < 256; ++idx)
    lookupHex[idx] = hexChars.charAt(idx >> 4) + hexChars.charAt(idx & 0xf);

  /*
 Convert a utf-8 string to hexadecimal digits
*/

  function asHex(data) {
    var result = "";
    let encoded = encodeURIComponent(data);
    for (let idx = 0; idx < encoded.length; ++idx) {
      let code = undefined;
      let ch = encoded[idx];
      if (ch == "%") {
        code = Number("0x" + encoded[idx + 1] + encoded[idx + 2]);
        idx += 2;
      } else code = ch.codePointAt(0);
      result += lookupHex[code];
    }
    return result;
  }

  function toHex(value) {
    return value.toString(16);
  }

  /*
 FIXME: These parameters aren't very browser-friendly
*/
  /*
// Certified safe primes (source: primes.utm.edu)  
  // #57461 [2006]
  var alpha =
    (BigInt(137211941292195) * BigInt(2) ** BigInt(171960) - BigInt(1)) *
      BigInt(2) +
    BigInt(1);

  // #59419 [2021]
  var beta =
    (BigInt(4318624617) * BigInt(2) ** BigInt(152849) - BigInt(1)) * BigInt(2) +
    BigInt(1);

  var block_size = 1 << 16;
*/

  /*
 "Highly-probable" safe primes generated by openssl:
  openssl prime -hex -safe -generate -bits 4096
 FIXME: May need to implement a `rounds` parameter or some
  such to prevent efficient brute-forcing of passphrase 
*/
  var alpha = BigInt(
    "0xF35FB68FD9157E652A93601E17F52FA89DF0A809A6953B99A5F5D449ACA2E3A4C3BE9F8E711060A29704675F93CA25FEE4A92E6A905627D89F9B877F6A997C218A66B4D6E8FCFE1B5F8F3FEF22344A4793059B72689B6A056E074789DAB06209F91FCD747763DB72C44FD2204E944877FA30D13A7C84252740642ACCDE25AFAD3701F5517923414F7E354FCD99ED5AF2D4808CB78CEB238711C7E7777932AD17C6E15EAD5534F5B9A1B9AC8769948D2DFC528B6AFE5668F90F0EEE119F0912EB409A4E9F3122C2E506CFC2754747027FFDF26E916DF15C69DFEECDD80ECDC53B0A08419D03E46039C23C9189A50A3FD1B83EE91D9F023C323DA78FFE5668B3D87304D800A75F6B01D226A583B829EE80D0CE10F56014FF723F10BF1E85DA769FEF936B973B2CC270754E8B0F055B80FE49FA09EE9E55B9C3054236B2E96E2C2DE42AD694081DEB64CC8AC4626CA3772E5FCD46FAB37399FBD5C41B5F6F378A9EC447823D27BB70BEE3ABE6E436CACDE10845597F35E3A86C3C5D0A654CA6953EB9C7953D5FB3F6B92221578E8949E77B710A6B4ECA891482A6BF1C7A9C2568D849384475B09DA1E87E554B66AD7EE2F8227970B4F10AB2082062AAB41EEFB1BFD0247B0DB9C6BA875EC4CD18D692DCEC243DF254C2A2B0DF8454A3888E42D8762470863922A3798DEEBFC37BE4E4EA2909140139CFD6B02672BAF0013391205B"
  );

  var beta = BigInt(
    "0xD00D945A9974833EB07CDFD88CBA78A0A27491E275B6B2BBA51CB130E2856B50DF1E08252B977806A92C969F39D4CA18FB4A39DB0B2CC6B70B197E35CCE6DC371BAC195E05FD189D12A3CF6FECE2CA9461ECF327D2E09FA8AA4BE05B7B7C4D362A28BEC2816B74BE0CCE76A3E3352CF27D117D01912DF68A62D0514551ABB6AF8896B2C9B2E1DC41C4029BB473F45ECC0BD1A10AF5ECB6E7C9F88CCC5AC8C8E8C1E1150E0B5718B37165D78F123E01F4B4D95D0CCFE2B6B6BD14D34F9E086B316F74027CFDF78813CBBEC09E414A1FA73FF5203C5550FD232D047752219BE0336F7FEE6FC4FE3CA1758FDEBC2613279CAE989D98A1052FE98BD47E2A791A0CB7200AAE60A1CEF5D61062144061AA4C46E69318E8871EBC90C2BE1A7630FE2A2A222EB4E6800DE1B630661D1BF8F42DB2A646AA102F29B9FB77D6CDD840475007208856F6508BB85CB0F7A3A5CFBA5B4707CEC30F36CA1709AAF9A7B3F331F1AAC590498B00BA69142423F51E055EE5F0AD1C05B2A47A3A9D16A7FB386C9092C8746EB6F23EE2DD0127C901953B1C9322457412BD7A2A758C6F65F66824180EB8D50941E1D0896E9E4AF7EF01DF06C8ACF9DA82C4867CFBB2CD69BDD26BCCE9147D75D15BF5AA8BA4AF1A3D47B337A1AC609AEB1496AD3877D76957CE416E324E8EF41F286EBF8882B90AB1424285A7C26C1998C6E8645B2AE035BB322CF63503"
  );

  var block_size = 4096 / 4;

  /*
 Separators, for immalleability purposes
*/

  var record_separator = asHex("\u001e");
  var field_separator = asHex("\u001c");

  /*
 Hash function interface
*/

  function hash(passphrase, salt, digits) {
    /*
 Configure hash function parameters
*/

    if (!digits) digits = 128;
    var keys = [passphrase];
    if (Array.isArray(salt)) Array.prototype.push.apply(keys, salt);
    else keys.push(salt);

    /*
 Concatenate passphrase with salt(s)
*/

    var merged = record_separator;
    for (var idx = 0, limit = keys.length; idx < limit; ++idx) {
      var next = keys[idx];
      if (next != null && next != "") merged += asHex(next);
      merged += field_separator;
    }
    var value = BigInt("0x" + merged);

    /*
  Build the result
*/
    var result = "";

    do {
      var buffer = "";
      do {
        // Stretch the current state
        var hexadecimal = value.toString(16);
        var stretched = hexadecimal;
        do {
          stretched += record_separator + hexadecimal;
        } while (stretched.length <= block_size);
        // Pass value through finite-field mapping
        value = (alpha * BigInt("0x" + stretched)) % beta;
        buffer += value.toString(16);
      } while (buffer.length <= block_size);

      /*
  Sponge construction; extract hash from our buffer
*/

      var current = buffer.length - 1;
      while (current > 2) {
        var offset =
          (lookupCode[buffer.codePointAt(current)] << 4) |
          lookupCode[buffer.codePointAt(current - 1)];
        current -= 2;
        if (current <= offset) break;
        current -= offset;
        result += buffer.charAt(current);
      }
      if (digits < 0) return result;
    } while (result.length < digits);
    return result.substr(0, digits);
  }

  /*
 Encode data as base-64 string
*/
  //TODO: Bounds checking
  function encode(passphrase, text) {
    if (text == null) text = "";
    var result = "";
    var buffer = "";
    for (var i = 0; i < 16; ++i)
      buffer += toHex(Math.floor(Math.random() * 0xffffffff));
    var seed = hash(passphrase, [buffer, new Date().getTime().toString()], 128);
    result += seed;
    var blob = "";
    var size = text.length;
    var shex = toHex(size);
    blob += lookupHex[shex.length][1];
    blob += shex;
    blob += asHex(text);
    var needed = blob.length + 1;
    var pad = "";
    var next = passphrase;
    while (pad.length <= needed) {
      next = hash(next, seed, -1);
      pad += next;
    }
    var index;
    for (index = 0; index < needed; ++index) {
      var lhs = lookupCode[blob.codePointAt(index)];
      var rhs = lookupCode[pad.codePointAt(index)];
      var xored = lhs ^ rhs;
      result += hexChars[xored];
    }
    while (index < pad.length)
      result += hexChars[lookupCode[pad.codePointAt(index++)]];
    // TODO: refactor
    return btoa(
      result
        .match(/\w{2}/g)
        .map(function (a) {
          return String.fromCharCode(parseInt(a, 16));
        })
        .join("")
    );
  }

  // TODO: refactor
  function base64ToHex(str) {
    const raw = atob(str);
    let result = "";
    for (let i = 0; i < raw.length; i++) {
      const hex = raw.charCodeAt(i).toString(16);
      result += hex.length === 2 ? hex : "0" + hex;
    }
    return result.toLowerCase();
  }

  /*
 Decode data from base-64 string
*/
  //TODO: Bounds checking
  function decode(passphrase, base64) {
    var result = "";
    var hex = base64ToHex(base64);
    var seed = hex.substr(0, 128);
    var encoded = hex.substr(128, base64.length);
    var elen = encoded.length;
    var pad = "";
    var next = passphrase;
    while (pad.length < elen) {
      next = hash(next, seed, -1);
      pad += next;
    }
    var index;
    var slen = 0;
    var hlen =
      lookupCode[encoded.codePointAt(0)] ^ lookupCode[pad.codePointAt(0)];
    for (index = 1; index <= hlen; ++index) {
      slen <<= 4;
      slen +=
        lookupCode[encoded.codePointAt(index)] ^
        lookupCode[pad.codePointAt(index)];
    }
    for (var count = 0; count < slen; ++count, index += 2) {
      var lhs = lookupCode[encoded.codePointAt(index)];
      var rhs = lookupCode[pad.codePointAt(index)];
      var xored = (lhs ^ rhs) << 4;
      lhs = lookupCode[encoded.codePointAt(index + 1)];
      rhs = lookupCode[pad.codePointAt(index + 1)];
      xored |= lhs ^ rhs;
      if (xored == 0) return null;
      result += String.fromCodePoint(xored);
    }
    do {
      var lhs = lookupCode[encoded.codePointAt(index)];
      var rhs = lookupCode[pad.codePointAt(index)];
      if ((lhs ^ rhs) != 0) return null;
    } while (++index < elen);
    return result;
  }

  function get(passphrase, domain) {
    if (entropis.storage == null) return {};
    var data = decode(passphrase, entropis.storage);
    if (data == null) return null;
    var datastore;
    try {
      datastore = JSON.parse(data);
    } catch (exception) {
      return null;
    }
    return domain == null ? datastore : datastore[domain];
  }

  function set(passphrase, domain, password) {
    var datastore = get(passphrase);
    if (datastore == null) return null;
    if (password === undefined) return null;
    if (password == null) delete datastore[domain];
    else datastore[domain] = password;
    return (entropis.storage = encode(passphrase, JSON.stringify(datastore)));
  }

  function remove(passphrase, domain) {
    return set(passphrase, domain, null);
  }

  function clear(passphrase) {
    if (passphrase != null && !get(passphrase)) return false;
    entropis.storage = null;
    return true;
  }

  function change(oldphrase, newphrase) {
    var datastore = get(oldphrase);
    if (datastore == null) return null;
    return (entropis.storage = encode(newphrase, JSON.stringify(datastore)));
  }

  return { hash, encode, decode, get, set, remove, clear, change };
})();

if (typeof module !== "undefined") module.exports = entropis;
else if (typeof define === "function" && define.amd)
  define(function () {
    return entropis;
  });
